In [2]:
import numpy as np

In [4]:
# generate an array of dimensions 20 times 10 times 3, with all values set to 0
# each 3-dimensional element having a 0.2 probability of having one number to 1 and the others to 0 and 0.8 probability of having all zeros

def generate_array(arr, size, p_distr):
    return np.random.choice(len(arr), size=size, p=p_distr)
    
arr = [[0,0,0], [1,0,0], [0,1,0], [0,0,1]]
size = (20,10)
p_distr = [0.6, 0.15, 0.15, 0.1]

In [12]:
indexes = generate_array(arr, size, p_distr)

In [13]:
# generate 3-dimensional matrix by substituting the indexes with the values
matrix = np.array(arr)[indexes]

In [14]:
matrix

array([[[0, 0, 0],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[1, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 0],
        [0, 1, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
  

In [35]:
def generate_patients(num, max_patients):
    return np.random.randint(1, max_patients+1, size=num)

def generate_visits(num, max_visits, p_distr=[0.5, 0.2, 0.3]):
    return np.random.choice(range(1, max_visits+1), size=num, p=p_distr)

def generate_timeslots(num, num_timeslots, ts_distr_array):
    sample_length = int(num / len(ts_distr_array))
    r = num % len(ts_distr_array)
    # generate samples and concat all samples in one matrix (num, num_timeslots
    first = True
    
    # variable for full matrix
    matrix = None

    for p_distr in ts_distr_array:
        if first:
            first = False
            sample_length += r

        samples = np.random.choice(2, size=(sample_length, num_timeslots), p=p_distr)
        # all samples must have at least one 1 per row
        for i in range(sample_length):
            if not np.any(samples[i]):
                samples[i][np.random.randint(0, num_timeslots)] = 1
                
        if matrix is None:
            matrix = samples
        else:
            matrix = np.concatenate((matrix, samples), axis=0)

    return matrix

def generate_priorities(num, p_distr=[0.8, 0.2]):
    return np.random.choice((1,2), size=num, p=p_distr)


def print_opl(elem):
    print("<{}, {}, {}, {}, {}>,".format(*elem))


def generate_requests(num, max_patients, max_visits, ts_distr_array, num_timeslots=10, p_distr=[0.8, 0.2]):
    patients = generate_patients(num, max_patients)
    visits = generate_visits(num, max_visits)

    timeslots = generate_timeslots(num, num_timeslots, ts_distr_array)
    priorities = generate_priorities(num)
    for elem in list(zip(range(1, num+1), patients, visits, timeslots, priorities)):
        print_opl(elem)

In [109]:
ts_distr_array = [
    [0,1],
    [0.1, 0.9],
    [0.2, 0.8],
    [0.3, 0.7],
    [0.4, 0.6],
    [0.5, 0.5],
    [0.6, 0.4],
    [0.7, 0.3],
    [0.8, 0.2],
    [0.9, 0.1]    
]

generate_requests(100, 20, 3, ts_distr_array)


<1, 8, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<2, 11, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<3, 5, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<4, 20, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<5, 11, 1, [1 1 1 1 1 1 1 1 1 1], 2>,
<6, 11, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<7, 17, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<8, 18, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<9, 12, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<10, 10, 2, [1 1 1 1 1 1 1 1 1 1], 1>,
<11, 9, 2, [1 1 1 1 1 1 1 1 1 1], 1>,
<12, 20, 1, [1 1 0 1 0 1 1 1 0 0], 1>,
<13, 6, 3, [1 1 0 0 1 1 1 0 1 0], 1>,
<14, 3, 3, [1 1 1 1 1 1 1 1 1 1], 2>,
<15, 9, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<16, 13, 1, [1 1 1 1 1 1 1 0 1 0], 1>,
<17, 12, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<18, 13, 2, [1 1 1 1 1 1 1 1 1 1], 1>,
<19, 3, 1, [1 1 1 1 1 1 0 1 1 1], 1>,
<20, 18, 3, [1 1 1 0 1 1 1 1 1 0], 1>,
<21, 1, 1, [1 1 1 0 0 1 1 1 0 1], 1>,
<22, 14, 1, [0 1 1 1 0 1 1 0 0 1], 1>,
<23, 20, 2, [1 1 0 0 1 1 1 1 1 1], 2>,
<24, 5, 1, [1 1 1 1 1 1 1 1 1 1], 2>,
<25, 11, 3, [0 1 1 0 1 1 1 0 1 1], 1>,
<26, 2, 3, [1 1 1 0 1 1 1 1 1 1], 1>,
<27, 

In [68]:
int(10/3)

3

// decision variables
dvar boolean scheduling[Requests][TimeSlots];
dvar boolean assignment[Patients][Operators];


// objective function: cost
dexpr float totalWage = sum(r in Requests, t in TimeSlots, o in Operators) assignment[r.patient][o] * visitTime[r.visit] * operatorWage[o];

/****************************************************************
	END DECISION VARIABLES AND EXPRESSIONS
****************************************************************/


/****************************************************************
	COMPUTATION
****************************************************************/

minimize totalWage;

subject to {
	// each visit must be done
	forall (r in Requests) {
        sum(t in TimeSlots) scheduling[r][t] == 1;
    }
    
    // the time slot of each visit must be feasible
    forall (r in Requests, t in TimeSlots){
    	scheduling[r][t] == 1 => r.timeSlots[t] == 1;
    }
    
    // the operator must be available when handling the request
    forall (r in Requests, t in TimeSlots, o in Operators){
    	scheduling[r][t] * assignment[r.patient][o] == 1 => operatorAvailability[o][t] == 1;
    }
    
    // the skill of the operator must be g.e. than the skill required for the visit
    forall (r in Requests, t in TimeSlots, o in Operators) {
        scheduling[r][t] * assignment[r.patient][o] == 1 => operatorSkill[o] >= visitSkill[r.visit];
    }
    
    // sum of visit times for all patients, visits, and operators should be l.e. than the time slot duration
	forall (t in TimeSlots, o in Operators)	{
	    sum(r in Requests) scheduling[r][t] * assignment[r.patient][o] * visitTime[r.visit] <= timeSlotDuration;
	}
	
	// sum of visit times for all patients, time slots, and visits should be less than or equal to the available working time of the operator.
	forall (o in Operators)	{
	    sum(r in Requests, t in TimeSlots) scheduling[r][t] * assignment[r.patient][o] * visitTime[r.visit] <= operatorTime[o];
	}
	
	// no operator works more than its daily time
	forall (o in Operators, d in Days) {
		sum(r in Requests, t in (2*d-1)..(2*d))(scheduling[r][t] * assignment[r.patient][o] * visitTime[r.visit]) <= maxDailyTime;
	}
	
//	// minimum global continuity
//	forall (p in Patients, t in TimeSlots, v in Visits, o in Operators){
//		assignment[p][t][v][o] * operatorSkill[o] >= assignment[p][t][v][o] * minGlobalContinuity[p];
//	}
//	
//	// care continuity constraint for same skill level visits
//	forall (p in Patients){
//		sum(
//			r1 in Requests,
//			r2 in Requests : visitSkill[r1.visit] == visitSkill[r2.visit] || (minGlobalContinuity[p] > visitSkill[r1.visit] || minGlobalContinuity[p] > visitSkill[r2.visit]),
//			t1 in TimeSlots,
//			t2 in TimeSlots : t1 != t2,
//			o1 in Operators,
//			o2 in Operators : o1 != o2)(assignment[r1][t1][o1] * assignment[r2][t2][o2]) <= 0;
//	}

	// minimum global continuity
	forall(p in Patients) {
		sum(o in Operators) assignment[p][o] == 1;
	}
};

In [11]:
# generate a 20x20 matrix of the commutation time among patients
# each element has a 0.2 probability of having a value between 1 and 10 and 0.8 probability of having a value between 11 and 20
# diagonal must be 0
# symmetric matrix
# each element must be an integer
# enforce triangular inequality

def generate_commutation_matrix(size=[27, 27]):
    # generate distances with gaussian distribution
    matrix = np.random.normal(18, 9, size=size)
    # convert to integer
    matrix = matrix.astype(int)
    # convert all negative numbers to 1
    matrix[matrix < 1] = 1
    # diagonal must be 0
    np.fill_diagonal(matrix, 0)
    # symmetric matrix
    matrix = np.triu(matrix) + np.triu(matrix, 1).T
    return matrix

comm_matrix = generate_commutation_matrix()
comm_matrix

array([[ 0, 21, 20,  5, 17, 22, 42,  4,  1, 30, 26, 28, 33, 22, 27, 26,
        21,  1, 10, 25,  1, 19, 13,  1, 18, 10, 16],
       [21,  0, 13, 30,  2, 32, 26, 14, 34, 13, 14,  1,  5, 25, 21, 17,
         8,  6, 30, 20, 25, 34, 10, 21, 25,  1, 12],
       [20, 13,  0,  9, 15, 13, 15, 10, 20, 14, 10, 10, 30,  1, 13,  1,
         9, 29, 35,  4, 25,  8, 24, 24, 15, 24, 26],
       [ 5, 30,  9,  0,  3, 16, 18,  3, 11,  2, 35, 14, 10, 22, 31, 25,
        26, 10, 23, 33, 11, 19, 20, 26, 21,  9, 22],
       [17,  2, 15,  3,  0, 21, 23, 23, 13, 18, 14, 19, 27, 14,  1, 19,
        34, 14,  6,  1,  5, 42, 18,  6,  3, 15, 25],
       [22, 32, 13, 16, 21,  0, 20, 28,  6, 17, 24, 16, 10,  9, 13, 26,
        13, 21,  8, 19,  5, 29,  3, 17,  4, 16,  1],
       [42, 26, 15, 18, 23, 20,  0, 18, 11, 12, 25, 26, 14, 18,  6, 25,
        13, 20, 28, 20, 14,  9, 11, 15, 15,  9, 16],
       [ 4, 14, 10,  3, 23, 28, 18,  0,  1, 14,  4, 21, 17, 15, 20, 15,
         2, 18, 14, 13, 27, 11,  6, 23, 17,  9, 17],


In [27]:
def print_opl_matrix(matrix):
    for row in matrix:
        print("[", end="")
        print(row[0], end="")
        for elem in row[1:]:
            print(f",{elem}", end="")
        print("],")

# print_opl_matrix(comm_matrix)

In [2]:
# generate 7 times 5 times 8 binary matrix
# each element has a 0.8 probability of having a value of 1 and 0.2 probability of having a value of 0
import numpy as np

def generate_binary_matrix(size=[7, 10], p_distr=[0.2, 0.8]):
    return np.random.choice(2, size=size, p=p_distr)

binary_matrix = generate_binary_matrix()
binary_matrix

array([[1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 1]])

In [4]:
bm = generate_binary_matrix([20, 10], [0.8, 0.2])
bm

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [7]:
bm = [
	[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
	[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
	[1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 1, 0, 0, 1, 1, 1, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
	[0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
	[0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
]

# generate 20x10 matrix of 1 and 2
# each element has a 0.8 probability of having a value of 1 and 0.2 probability of having a value of 2

def generate_matrix(size=[20, 10], p_distr=[0.8, 0.2]):
    return np.random.choice((1,2), size=size, p=p_distr)

matrix = generate_matrix()

# pointwise multiply the two matrices
# the result is a 20x10 matrix of 0, 1 and 2

def pointwise_multiply(m1, m2):
    return np.multiply(m1, m2)

result = pointwise_multiply(bm, matrix)
result

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 2, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0]])

In [29]:
# generate matrix 20x10 with uniform distribution between 0 and 42

def generate_uniform_matrix(size=[20, 10], low=0, high=42):
    return np.random.randint(low, high, size=size)

um = generate_uniform_matrix()
vst = pointwise_multiply(bm, um*5 + 30)
vst

array([[150,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  35,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 225,   0,   0,   0,   0,   0,   0],
       [  0, 190, 210,  45,   0, 120,   0,  30, 125,   0],
       [  0,   0,   0,   0,   0,  45,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 175,   0,   0,   0,   0],
       [  0, 195,   0,   0,   0, 160,   0,   0,   0,  35],
       [105,   0,   0,   0,   0,   0,   0,   0,   0, 210],
       [  0, 230,   0,   0, 110, 110,  45,   0,   0,  90],
       [  0,   0,   0, 175,   0,   0, 160,   0,   0,   0],
       [  0, 235,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 160, 200,   0,   0,   0,   0,  60],
       [  0,   0,   0,   0,   0, 150, 110,  30,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 220],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 105],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 210],
       [  0,   0, 195,   0,   0,   0,   0,   0,   0,   0

In [ ]:
oa = [
    [1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
	[0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
	[0, 1, 1, 1, 0, 1, 1, 1, 0, 1],
	[1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
	[1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
	[1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
	[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
]

# generate 7x10 matrix 

In [45]:
def generate_requests(num_patients, num_days, num_timeslots, num_visits, prob=0.5):
    requests = []
    index = 1
    for patient in range(1, num_patients+1):
        for day in range(1, num_days+1):
            # random variable between 0 and 1
            if np.random.rand() > prob:
                timeslot = np.random.randint(1, num_timeslots+1)
                visit = np.random.choice(range(1, num_visits + 1), p=[0.55, 0.35, 0.1])
                requests.append((index, patient, visit, day, timeslot))
                index += 1

    return requests

In [46]:
b = generate_requests(20, 5, 8, 3)

for e in b:
    print_opl(e)

<1, 1, 2, 1, 5>,
<2, 1, 2, 2, 8>,
<3, 2, 1, 1, 3>,
<4, 2, 2, 2, 8>,
<5, 2, 1, 3, 3>,
<6, 2, 1, 5, 3>,
<7, 3, 1, 2, 6>,
<8, 3, 2, 3, 5>,
<9, 3, 2, 5, 6>,
<10, 4, 2, 2, 6>,
<11, 4, 3, 4, 5>,
<12, 4, 1, 5, 6>,
<13, 6, 2, 2, 5>,
<14, 7, 1, 3, 3>,
<15, 8, 1, 2, 6>,
<16, 9, 3, 2, 8>,
<17, 9, 1, 3, 8>,
<18, 9, 2, 4, 5>,
<19, 10, 2, 2, 1>,
<20, 10, 1, 5, 8>,
<21, 11, 1, 2, 1>,
<22, 11, 1, 3, 7>,
<23, 11, 1, 4, 5>,
<24, 11, 1, 5, 5>,
<25, 12, 1, 2, 3>,
<26, 12, 1, 3, 4>,
<27, 12, 1, 4, 4>,
<28, 12, 1, 5, 5>,
<29, 13, 2, 1, 6>,
<30, 13, 1, 2, 6>,
<31, 13, 2, 3, 7>,
<32, 13, 3, 4, 5>,
<33, 13, 1, 5, 4>,
<34, 14, 1, 4, 4>,
<35, 14, 1, 5, 8>,
<36, 15, 1, 3, 3>,
<37, 15, 1, 4, 3>,
<38, 16, 2, 3, 8>,
<39, 16, 1, 5, 7>,
<40, 17, 2, 1, 5>,
<41, 17, 1, 4, 5>,
<42, 17, 2, 5, 3>,
<43, 18, 1, 2, 3>,
<44, 18, 2, 5, 1>,
<45, 19, 1, 1, 1>,
<46, 19, 1, 2, 4>,
<47, 20, 1, 1, 3>,
<48, 20, 2, 2, 2>,
<49, 20, 2, 4, 7>,
<50, 20, 1, 5, 6>,


In [30]:
np.random.rand()

0.2607119719264961

In [10]:
# generate 27 2-dimensional points in the space [0, 100]x[0, 100] and compute the matrix of distances among them
import numpy as np

def generate_points(size=7):
    return np.random.randint(0, 21, size=size)

points = generate_points(20)
points


array([ 5, 19,  6,  7,  9,  2, 14,  6, 16, 11,  7,  8, 14,  7,  0, 17,  8,
       13,  4, 11])

In [8]:
# generate matrix of distances among points
def generate_distances(points):
    return np.linalg.norm(points[:, None] - points, axis=-1)

distances = generate_distances(points)   
distances

array([[ 0.        ,  9.43398113,  8.        , 13.60147051,  5.38516481,
         5.09901951, 23.60084744, 23.76972865, 12.64911064, 10.81665383,
        12.08304597, 24.16609195, 10.19803903, 17.69180601, 10.77032961,
        20.        , 12.20655562, 19.6468827 ,  1.41421356, 16.1245155 ,
        18.02775638, 12.        , 22.36067977, 21.40093456,  7.28010989,
         7.61577311, 18.02775638],
       [ 9.43398113,  0.        , 15.26433752, 22.627417  , 13.34166406,
        12.20655562, 32.55764119, 31.90611227,  9.8488578 , 11.04536102,
        10.44030651, 32.44996148, 19.31320792, 17.72004515, 20.1246118 ,
        26.2488095 , 18.11077028, 27.29468813,  9.8488578 , 23.2594067 ,
        20.09975124, 20.61552813, 29.54657341, 30.41381265,  7.07106781,
        13.        , 26.90724809],
       [ 8.        , 15.26433752,  0.        ,  8.54400375, 11.18033989,
         3.16227766, 17.80449381, 16.64331698, 12.64911064,  9.21954446,
        11.40175425, 17.20465053, 11.66190379, 13.6014

In [14]:
# convert distances to int
distances = distances.astype(int)
# print distances as a compact array of arrays
print_opl_matrix(distances)

[0,9,8,13,5,5,23,23,12,10,12,24,10,17,10,20,12,19,1,16,18,12,22,21,7,7,18],
[9,0,15,22,13,12,32,31,9,11,10,32,19,17,20,26,18,27,9,23,20,20,29,30,7,13,26],
[8,15,0,8,11,3,17,16,12,9,11,17,11,13,10,12,18,12,9,8,12,14,14,15,9,3,12],
[13,22,8,0,13,10,10,11,21,17,19,11,9,21,7,12,18,8,13,7,18,11,11,7,17,11,4],
[5,13,11,13,0,9,22,24,18,16,17,24,6,22,7,22,7,21,4,18,22,7,24,20,12,12,17],
[5,12,3,10,9,0,20,19,11,8,10,20,11,13,11,15,16,15,6,11,13,13,17,18,6,2,14],
[23,32,17,10,22,20,0,5,30,26,28,5,17,27,15,14,26,9,23,12,24,19,10,2,27,20,5],
[23,31,16,11,24,19,5,0,27,24,26,1,20,24,18,9,29,5,24,9,20,22,5,6,25,19,7],
[12,9,12,21,18,11,30,27,0,3,1,28,22,8,22,20,24,22,13,18,11,24,24,28,5,9,24],
[10,11,9,17,16,8,26,24,3,0,2,24,19,7,19,16,23,19,12,14,9,21,20,24,4,6,21],
[12,10,11,19,17,10,28,26,1,2,0,27,21,7,21,18,24,21,13,17,10,23,22,26,5,8,23],
[24,32,17,11,24,20,5,1,28,24,27,0,20,25,18,10,29,5,24,10,21,22,6,5,26,19,7],
[10,19,11,9,6,11,17,20,22,19,21,20,0,25,2,20,9,17,9,16,23,2,20,15,17,13,13],
[17,1