In [2]:
import numpy as np

In [4]:
# generate an array of dimensions 20 times 10 times 3, with all values set to 0
# each 3-dimensional element having a 0.2 probability of having one number to 1 and the others to 0 and 0.8 probability of having all zeros

def generate_array(arr, size, p_distr):
    return np.random.choice(len(arr), size=size, p=p_distr)
    
arr = [[0,0,0], [1,0,0], [0,1,0], [0,0,1]]
size = (20,10)
p_distr = [0.6, 0.15, 0.15, 0.1]

In [12]:
indexes = generate_array(arr, size, p_distr)

In [13]:
# generate 3-dimensional matrix by substituting the indexes with the values
matrix = np.array(arr)[indexes]

In [14]:
matrix

array([[[0, 0, 0],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[1, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 0],
        [0, 1, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
  

In [35]:
def generate_patients(num, max_patients):
    return np.random.randint(1, max_patients+1, size=num)

def generate_visits(num, max_visits, p_distr=[0.5, 0.2, 0.3]):
    return np.random.choice(range(1, max_visits+1), size=num, p=p_distr)

def generate_timeslots(num, num_timeslots, ts_distr_array):
    sample_length = int(num / len(ts_distr_array))
    r = num % len(ts_distr_array)
    # generate samples and concat all samples in one matrix (num, num_timeslots
    first = True
    
    # variable for full matrix
    matrix = None

    for p_distr in ts_distr_array:
        if first:
            first = False
            sample_length += r

        samples = np.random.choice(2, size=(sample_length, num_timeslots), p=p_distr)
        # all samples must have at least one 1 per row
        for i in range(sample_length):
            if not np.any(samples[i]):
                samples[i][np.random.randint(0, num_timeslots)] = 1
                
        if matrix is None:
            matrix = samples
        else:
            matrix = np.concatenate((matrix, samples), axis=0)

    return matrix

def generate_priorities(num, p_distr=[0.8, 0.2]):
    return np.random.choice((1,2), size=num, p=p_distr)


def print_opl(elem):
    print("<{}, {}, {}, {}, {}>,".format(*elem))


def generate_requests(num, max_patients, max_visits, ts_distr_array, num_timeslots=10, p_distr=[0.8, 0.2]):
    patients = generate_patients(num, max_patients)
    visits = generate_visits(num, max_visits)

    timeslots = generate_timeslots(num, num_timeslots, ts_distr_array)
    priorities = generate_priorities(num)
    for elem in list(zip(range(1, num+1), patients, visits, timeslots, priorities)):
        print_opl(elem)

In [109]:
ts_distr_array = [
    [0,1],
    [0.1, 0.9],
    [0.2, 0.8],
    [0.3, 0.7],
    [0.4, 0.6],
    [0.5, 0.5],
    [0.6, 0.4],
    [0.7, 0.3],
    [0.8, 0.2],
    [0.9, 0.1]    
]

generate_requests(100, 20, 3, ts_distr_array)


<1, 8, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<2, 11, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<3, 5, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<4, 20, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<5, 11, 1, [1 1 1 1 1 1 1 1 1 1], 2>,
<6, 11, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<7, 17, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<8, 18, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<9, 12, 1, [1 1 1 1 1 1 1 1 1 1], 1>,
<10, 10, 2, [1 1 1 1 1 1 1 1 1 1], 1>,
<11, 9, 2, [1 1 1 1 1 1 1 1 1 1], 1>,
<12, 20, 1, [1 1 0 1 0 1 1 1 0 0], 1>,
<13, 6, 3, [1 1 0 0 1 1 1 0 1 0], 1>,
<14, 3, 3, [1 1 1 1 1 1 1 1 1 1], 2>,
<15, 9, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<16, 13, 1, [1 1 1 1 1 1 1 0 1 0], 1>,
<17, 12, 3, [1 1 1 1 1 1 1 1 1 1], 1>,
<18, 13, 2, [1 1 1 1 1 1 1 1 1 1], 1>,
<19, 3, 1, [1 1 1 1 1 1 0 1 1 1], 1>,
<20, 18, 3, [1 1 1 0 1 1 1 1 1 0], 1>,
<21, 1, 1, [1 1 1 0 0 1 1 1 0 1], 1>,
<22, 14, 1, [0 1 1 1 0 1 1 0 0 1], 1>,
<23, 20, 2, [1 1 0 0 1 1 1 1 1 1], 2>,
<24, 5, 1, [1 1 1 1 1 1 1 1 1 1], 2>,
<25, 11, 3, [0 1 1 0 1 1 1 0 1 1], 1>,
<26, 2, 3, [1 1 1 0 1 1 1 1 1 1], 1>,
<27, 

In [68]:
int(10/3)

3

// decision variables
dvar boolean scheduling[Requests][TimeSlots];
dvar boolean assignment[Patients][Operators];


// objective function: cost
dexpr float totalWage = sum(r in Requests, t in TimeSlots, o in Operators) assignment[r.patient][o] * visitTime[r.visit] * operatorWage[o];

/****************************************************************
	END DECISION VARIABLES AND EXPRESSIONS
****************************************************************/


/****************************************************************
	COMPUTATION
****************************************************************/

minimize totalWage;

subject to {
	// each visit must be done
	forall (r in Requests) {
        sum(t in TimeSlots) scheduling[r][t] == 1;
    }
    
    // the time slot of each visit must be feasible
    forall (r in Requests, t in TimeSlots){
    	scheduling[r][t] == 1 => r.timeSlots[t] == 1;
    }
    
    // the operator must be available when handling the request
    forall (r in Requests, t in TimeSlots, o in Operators){
    	scheduling[r][t] * assignment[r.patient][o] == 1 => operatorAvailability[o][t] == 1;
    }
    
    // the skill of the operator must be g.e. than the skill required for the visit
    forall (r in Requests, t in TimeSlots, o in Operators) {
        scheduling[r][t] * assignment[r.patient][o] == 1 => operatorSkill[o] >= visitSkill[r.visit];
    }
    
    // sum of visit times for all patients, visits, and operators should be l.e. than the time slot duration
	forall (t in TimeSlots, o in Operators)	{
	    sum(r in Requests) scheduling[r][t] * assignment[r.patient][o] * visitTime[r.visit] <= timeSlotDuration;
	}
	
	// sum of visit times for all patients, time slots, and visits should be less than or equal to the available working time of the operator.
	forall (o in Operators)	{
	    sum(r in Requests, t in TimeSlots) scheduling[r][t] * assignment[r.patient][o] * visitTime[r.visit] <= operatorTime[o];
	}
	
	// no operator works more than its daily time
	forall (o in Operators, d in Days) {
		sum(r in Requests, t in (2*d-1)..(2*d))(scheduling[r][t] * assignment[r.patient][o] * visitTime[r.visit]) <= maxDailyTime;
	}
	
//	// minimum global continuity
//	forall (p in Patients, t in TimeSlots, v in Visits, o in Operators){
//		assignment[p][t][v][o] * operatorSkill[o] >= assignment[p][t][v][o] * minGlobalContinuity[p];
//	}
//	
//	// care continuity constraint for same skill level visits
//	forall (p in Patients){
//		sum(
//			r1 in Requests,
//			r2 in Requests : visitSkill[r1.visit] == visitSkill[r2.visit] || (minGlobalContinuity[p] > visitSkill[r1.visit] || minGlobalContinuity[p] > visitSkill[r2.visit]),
//			t1 in TimeSlots,
//			t2 in TimeSlots : t1 != t2,
//			o1 in Operators,
//			o2 in Operators : o1 != o2)(assignment[r1][t1][o1] * assignment[r2][t2][o2]) <= 0;
//	}

	// minimum global continuity
	forall(p in Patients) {
		sum(o in Operators) assignment[p][o] == 1;
	}
};

In [11]:
# generate a 20x20 matrix of the commutation time among patients
# each element has a 0.2 probability of having a value between 1 and 10 and 0.8 probability of having a value between 11 and 20
# diagonal must be 0
# symmetric matrix
# each element must be an integer
# enforce triangular inequality

def generate_commutation_matrix(size=[27, 27]):
    # generate distances with gaussian distribution
    matrix = np.random.normal(18, 9, size=size)
    # convert to integer
    matrix = matrix.astype(int)
    # convert all negative numbers to 1
    matrix[matrix < 1] = 1
    # diagonal must be 0
    np.fill_diagonal(matrix, 0)
    # symmetric matrix
    matrix = np.triu(matrix) + np.triu(matrix, 1).T
    return matrix

comm_matrix = generate_commutation_matrix()
comm_matrix

array([[ 0, 21, 20,  5, 17, 22, 42,  4,  1, 30, 26, 28, 33, 22, 27, 26,
        21,  1, 10, 25,  1, 19, 13,  1, 18, 10, 16],
       [21,  0, 13, 30,  2, 32, 26, 14, 34, 13, 14,  1,  5, 25, 21, 17,
         8,  6, 30, 20, 25, 34, 10, 21, 25,  1, 12],
       [20, 13,  0,  9, 15, 13, 15, 10, 20, 14, 10, 10, 30,  1, 13,  1,
         9, 29, 35,  4, 25,  8, 24, 24, 15, 24, 26],
       [ 5, 30,  9,  0,  3, 16, 18,  3, 11,  2, 35, 14, 10, 22, 31, 25,
        26, 10, 23, 33, 11, 19, 20, 26, 21,  9, 22],
       [17,  2, 15,  3,  0, 21, 23, 23, 13, 18, 14, 19, 27, 14,  1, 19,
        34, 14,  6,  1,  5, 42, 18,  6,  3, 15, 25],
       [22, 32, 13, 16, 21,  0, 20, 28,  6, 17, 24, 16, 10,  9, 13, 26,
        13, 21,  8, 19,  5, 29,  3, 17,  4, 16,  1],
       [42, 26, 15, 18, 23, 20,  0, 18, 11, 12, 25, 26, 14, 18,  6, 25,
        13, 20, 28, 20, 14,  9, 11, 15, 15,  9, 16],
       [ 4, 14, 10,  3, 23, 28, 18,  0,  1, 14,  4, 21, 17, 15, 20, 15,
         2, 18, 14, 13, 27, 11,  6, 23, 17,  9, 17],


In [15]:
def print_opl_matrix(matrix):
    for row in matrix:
        print("[", end="")
        print(row[0], end="")
        for elem in row[1:]:
            print(f",{elem}", end="")
        print("],")

print_opl_matrix(comm_matrix)

[0,21,20,5,17,22,42,4,1,30,26,28,33,22,27,26,21,1,10,25,1,19,13,1,18,10,16],
[21,0,13,30,2,32,26,14,34,13,14,1,5,25,21,17,8,6,30,20,25,34,10,21,25,1,12],
[20,13,0,9,15,13,15,10,20,14,10,10,30,1,13,1,9,29,35,4,25,8,24,24,15,24,26],
[5,30,9,0,3,16,18,3,11,2,35,14,10,22,31,25,26,10,23,33,11,19,20,26,21,9,22],
[17,2,15,3,0,21,23,23,13,18,14,19,27,14,1,19,34,14,6,1,5,42,18,6,3,15,25],
[22,32,13,16,21,0,20,28,6,17,24,16,10,9,13,26,13,21,8,19,5,29,3,17,4,16,1],
[42,26,15,18,23,20,0,18,11,12,25,26,14,18,6,25,13,20,28,20,14,9,11,15,15,9,16],
[4,14,10,3,23,28,18,0,1,14,4,21,17,15,20,15,2,18,14,13,27,11,6,23,17,9,17],
[1,34,20,11,13,6,11,1,0,15,5,14,11,26,33,22,35,15,33,12,24,9,15,10,2,27,14],
[30,13,14,2,18,17,12,14,15,0,27,19,7,11,13,8,22,12,29,27,17,7,22,24,28,33,22],
[26,14,10,35,14,24,25,4,5,27,0,24,11,29,13,10,32,25,29,27,2,25,7,28,18,12,18],
[28,1,10,14,19,16,26,21,14,19,24,0,19,5,16,13,6,17,27,4,1,12,31,22,10,24,1],
[33,5,30,10,27,10,14,17,11,7,11,19,0,23,30,13,19,7,10,28,18,19,8,26,33,26

In [40]:
# generate 7 times 5 times 8 binary matrix
# each element has a 0.8 probability of having a value of 1 and 0.2 probability of having a value of 0

def generate_binary_matrix(size=[7, 5, 8], p_distr=[0.2, 0.8]):
    return np.random.choice(2, size=size, p=p_distr)

binary_matrix = generate_binary_matrix()
binary_matrix

array([[[0, 1, 0, 0, 0, 1, 1, 1],
        [1, 1, 0, 1, 1, 0, 1, 1],
        [0, 1, 1, 1, 1, 1, 1, 0],
        [1, 0, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 0, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 0, 0, 1, 0],
        [1, 0, 1, 1, 1, 0, 1, 1]],

       [[1, 1, 0, 1, 1, 1, 1, 0],
        [1, 1, 1, 0, 0, 1, 1, 0],
        [0, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 0, 1, 1],
        [0, 0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 1, 1, 1, 1, 0],
        [0, 1, 1, 0, 0, 1, 1, 1]],

       [[1, 1, 1, 0, 1, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 1, 1, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 0, 1],
        [1, 1, 0, 1, 1, 0, 1, 1],
        [0, 0, 1, 1, 1, 1, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
    

In [38]:
def generate_requests(num_patients, num_days, num_timeslots, num_visits, prob=0.3):
    requests = []
    index = 1
    for patient in range(1, num_patients+1):
        for day in range(1, num_days+1):
            # random variable between 0 and 1
            if np.random.rand() > prob:
                timeslot = np.random.randint(1, num_timeslots+1)
                visit = np.random.choice(range(1, num_visits + 1), p_distr=[0.55, 0.35, 0.1])
                requests.append((index, patient, visit, day, timeslot))
                index += 1

    return requests

In [39]:
b = generate_requests(20, 5, 8, 3)

for e in b:
    print_opl(e)

<1, 1, 2, 1, 1>,
<2, 1, 3, 2, 1>,
<3, 1, 3, 3, 8>,
<4, 1, 3, 5, 8>,
<5, 2, 2, 1, 4>,
<6, 2, 3, 2, 8>,
<7, 2, 2, 3, 5>,
<8, 2, 2, 4, 7>,
<9, 2, 1, 5, 5>,
<10, 3, 2, 1, 5>,
<11, 3, 3, 2, 8>,
<12, 3, 1, 4, 5>,
<13, 4, 1, 2, 4>,
<14, 4, 1, 4, 2>,
<15, 4, 3, 5, 7>,
<16, 5, 3, 1, 1>,
<17, 5, 2, 2, 5>,
<18, 5, 1, 4, 7>,
<19, 5, 3, 5, 3>,
<20, 6, 3, 1, 5>,
<21, 6, 2, 2, 1>,
<22, 6, 2, 4, 8>,
<23, 6, 3, 5, 6>,
<24, 7, 2, 2, 2>,
<25, 7, 3, 3, 6>,
<26, 7, 2, 4, 5>,
<27, 7, 3, 5, 8>,
<28, 8, 2, 1, 5>,
<29, 8, 2, 3, 2>,
<30, 8, 3, 4, 5>,
<31, 9, 3, 3, 6>,
<32, 9, 1, 5, 8>,
<33, 10, 2, 1, 7>,
<34, 10, 3, 2, 6>,
<35, 10, 2, 3, 1>,
<36, 10, 2, 4, 8>,
<37, 10, 3, 5, 7>,
<38, 11, 3, 1, 4>,
<39, 11, 2, 2, 3>,
<40, 11, 1, 3, 6>,
<41, 11, 2, 5, 1>,
<42, 12, 1, 1, 3>,
<43, 12, 3, 2, 2>,
<44, 12, 1, 3, 8>,
<45, 12, 2, 4, 4>,
<46, 12, 2, 5, 1>,
<47, 13, 1, 1, 7>,
<48, 13, 3, 3, 8>,
<49, 13, 3, 5, 1>,
<50, 14, 3, 1, 6>,
<51, 14, 1, 2, 3>,
<52, 14, 1, 4, 4>,
<53, 15, 1, 1, 5>,
<54, 15, 1, 2, 4>,
<55, 15, 2, 5, 

In [30]:
np.random.rand()

0.2607119719264961